# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from tkinter import *
import requests
import os
import urllib.request
import os.path



from PyQt5 import QtCore, QtGui, QtWidgets


def createTempFolder():
    directory ="C:\Ziitech"
    if not os.path.exists(directory):
        os.makedirs(directory)
    else:
        print("yes")

def DDAInstallationProcess(FileToInstall):
    print("start")
    runCMD1='cmd /c taskkill /IM "AssistantServer(v1.2.1).exe" /F'
    runCMD2='cmd /c taskkill /IM "ZiiPOSClassicRetail.exe" /F'
    runCMD3="cmd /c" + FileToInstall + " /S"
    os.system(runCMD1)
    os.system(runCMD2)
    os.system(runCMD3)
    exit();


def downloadZiiPOSRetail(dornloadURL,filePath):
    #filePath = path+"\ZiiPOSRetail"+version+".exe"
    urllib.request.urlretrieve(dornloadURL, filePath)
    file_exists = os.path.exists(filePath)
    if (file_exists==True):
        DDAInstallationProcess(filePath)
    else:
        print("Error")


    



def getDDAVersion():
    URL = "https://wombat-api.ziicloud.com/api/vs/client-version/version?clientName=Zii.Retail_Classic&version=1"
    r = requests.get(url = URL)
    data = r.json()
    version = str(data['data']['versionValue'])
    downloadurl=data['data']['upgradeUrl']
    print(downloadurl)
    createTempFolder()
    directory ="C:\Ziitech"
    filePath = "C:\Ziitech\ZiiPOSRetail"+version+".exe"
    downloadZiiPOSRetail(downloadurl,filePath)
    


class Ui_MainWindow(object):
    

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(252, 156)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.getZiiPOSretailUpgrade = QtWidgets.QPushButton(self.centralwidget)
        self.getZiiPOSretailUpgrade.setGeometry(QtCore.QRect(50, 20, 161, 61))
        self.getZiiPOSretailUpgrade.setObjectName("getZiiPOSretailUpgrade")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 252, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.getZiiPOSretailUpgrade.clicked.connect(getDDAVersion)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZiiPOS Upgrade assistance"))
        self.getZiiPOSretailUpgrade.setText(_translate("MainWindow", "Get Upgrade For ZiiPOS Retail"))



if __name__ == "__main__":
    import sys
   

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


